version: "3.9"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      #- NEUTRON_URL=http://devstack-public-ip:9696/v2.0/networks  
      - NEUTRON_URL=http://192.168.1.79:9696/networking/v2.0/networks
